name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          set -x
          mkdir -p ~/.ssh || { echo "mkdir failed"; exit 1; }
          if [ -z "$SSH_PRIVATE_KEY" ]; then echo "SSH_PRIVATE_KEY is empty"; exit 1; fi
          if [ -z "$HOST" ]; then echo "HOST is empty"; exit 1; fi
          if [ -z "$USER" ]; then echo "USER is empty"; exit 1; fi
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key.pem || { echo "echo failed"; exit 1; }
          chmod 600 ~/.ssh/private_key.pem || { echo "chmod failed"; exit 1; }
          ls -l ~/.ssh/private_key.pem
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts || { echo "ssh-keyscan failed"; exit 1; }

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          set -x
          ssh -i ~/.ssh/private_key.pem $USER@$HOST << 'EOF'
            cd /home/ubuntu/traffic-app-server || { echo "Directory not found"; exit 1; }
            git fetch origin || { echo "git fetch failed"; exit 1; }
            git reset --hard origin/main || { echo "git reset failed"; exit 1; }
            git status
            npm install || { echo "npm install failed"; exit 1; }
            pm2 restart traffic-app-v1 || pm2 start wss_server.js --name traffic-app-v1 || { echo "pm2 failed"; exit 1; }
          EOF
